[package]
name = "arceboot"
version = "0.0.1"
edition = "2024"
authors = ["Zhihang Shao <dio_ro@outlook.com>", "Jingxuan Wei <jensenwei007@gmail.com>"]

[features]
default = ["alloc", "fs", "paging", "disk"]

alloc = ["axalloc"]
paging = ["axhal/paging", "axmm"]

fs = ["axdriver", "axfs"]
net = ["axdriver", "axnet"]
display = ["axdriver", "axdisplay"]

disk = ["axdriver/virtio-blk"]

[dependencies]
axhal = { git = "https://github.com/arceos-org/arceos.git" }
axlog = { git = "https://github.com/arceos-org/arceos.git" }
axconfig = { git = "https://github.com/arceos-org/arceos.git" }
axalloc = { git = "https://github.com/arceos-org/arceos.git", optional = true }
axmm = { git = "https://github.com/arceos-org/arceos.git", optional = true }
axdriver = { git = "https://github.com/arceos-org/arceos.git", optional = true }
axfs = { git = "https://github.com/arceos-org/arceos.git", optional = true }
axnet = { git = "https://github.com/arceos-org/arceos.git", optional = true }
axdisplay = { git = "https://github.com/arceos-org/arceos.git", optional = true }

crate_interface = "0.1"
ctor_bare = "0.2"

chrono = { version = "0.4.38", default-features = false }
